xposweb/xposweb/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using Xpos.Models;
using xposapi.DataModels;

namespace xposweb.Controllers
{
    public class CategoriesController : Controller
    {
        private CategoriesModels category;
            
        public CategoriesController(IConfiguration _config)
        {
            category = new CategoriesModels(_config["ApiMasterUrl"]);
        }

        public IActionResult Index(string filter)
        {
            List<VMTblMCategory>? data;
            if (filter == null)
            {
                 data = category.GetAll();
            }
            else
            {
                data = category.GetBy(filter);
            }
            ViewBag.Title = "Category List";


            return View(data);
        }

        public IActionResult Details(int id)
        {
            ViewBag.Title = "Category Details";

            VMTblMCategory? data = category.GetById(id);

            return View(data);
        }

        public IActionResult Create() 
        {
            ViewBag.Title = "Create Category";
            return View();

        }

        [HttpPost]
        public VMTblMCategory Add(VMTblMCategory data)
        {
            VMTblMCategory newData = category.Create(data);

            return newData;
        }

        public IActionResult Update()
        {
            ViewBag.Title = "Update Category";
            return View();

        }
        [HttpPut]
        public VMTblMCategory? Updated(VMTblMCategory data)
        {
            VMTblMCategory? newData = category.Create(data);

            return newData;

        }

        public IActionResult Delete(int id)
        {
            ViewBag.Title = "Delete Category";
            return View(id);
        }
        [HttpDelete]
        public VMTblMCategory? Deleted(VMTblMCategory data) => category.Delete(data.Id, (int)data.UpdateBy!);




    }
}

xposweb/xposweb/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Xpos.Models;
using xposapi.DataModels;
using xposweb.AddOns;
using xposweb.Models;

namespace xposweb.Controllers
{
    public class ProductsController : Controller
    {
        private ProductsModel product;
        private VariantsModels variant;
        private CategoriesModels category;
        private readonly string imgFolder;
        private readonly int pageSize;

        public ProductsController(IConfiguration _config, IWebHostEnvironment _webHostEnv)
        {
            product = new ProductsModel(_config["ApiMasterUrl"], _webHostEnv);
            variant = new VariantsModels(_config["ApiMasterUrl"]);
            category = new CategoriesModels(_config["ApiMasterUrl"]);
            imgFolder = _config["ImageFolder"];
            pageSize = int.Parse(_config["PageSize"]);
        }

        public IActionResult Index(string? filter, string? orderBy, int? pageNumber, int? currPageSize)
        {
            List<VMTblMProduct>? data;
            int totalData = 0;

            if (string.IsNullOrEmpty(filter))
            {
                List<object> pagingData = product.GetAllPaging(pageNumber ?? 1, currPageSize ?? pageSize);

                data = JsonConvert.DeserializeObject <List<VMTblMProduct>?>(JsonConvert.SerializeObject(pagingData[0]));
                totalData = JsonConvert.DeserializeObject <int>(JsonConvert.SerializeObject(pagingData[1]));
            }
            else
            {
                data = product.GetBy(filter);
            }

            switch (orderBy)
            {
                case "stock_desc":
                    data = data.OrderByDescending(p => p.Stock).ToList();
                    break;
                case "stock":
                    data = data.OrderBy(p => p.Stock).ToList();
                    break;
                case "price_desc":
                    data = data.OrderByDescending(p => p.Price).ToList();
                    break;
                case "price":
                    data = data.OrderBy(p => p.Price).ToList();
                    break;
                case "productname_desc":
                    data = data.OrderByDescending(p => p.ProductName).ToList();
                    break;
                case "productname":
                    data = data.OrderBy(p => p.ProductName).ToList();
                    break;
                case "id_desc":
                    data = data.OrderByDescending(p => p.Id).ToList();
                    break;
                default:
                    data = data.OrderBy(p => p.Id).ToList();
                    break;
            }


            ViewBag.Title = "Product List";
            ViewBag.ImgFolder = imgFolder;

            //current page
            ViewBag.Filter = filter;
            ViewBag.OrderBy = orderBy;
            ViewBag.PageSize = currPageSize ?? pageSize;

            //update order selection
            ViewBag.orderId = string.IsNullOrEmpty(orderBy) ? "id_desc" : "" ;
            ViewBag.orderName = string.IsNullOrEmpty(orderBy) ? "productname_desc" : "";
            ViewBag.orderPrice = string.IsNullOrEmpty(orderBy) ? "price_desc" : "";
            ViewBag.orderStock = string.IsNullOrEmpty(orderBy) ? "stock_desc" : "";


            return View(Pagination<VMTblMProduct>.Create(data, totalData, pageNumber ?? 1, ViewBag.PageSize));
        }


        public IActionResult Details(int id)
        {
            ViewBag.Title = "Product Details";

            VMTblMProduct? data = product.GetById(id);

            return View(data);
        }

        public IActionResult Create()
        {
            ViewBag.catData = category.GetAll().Select(
                 c => new SelectListItem
                 {
                     Value = c.Id.ToString(),
                     Text = c.CategoryName
                 }).ToList();

            ViewBag.varData = variant.GetAll();

            return View();

        }

        [HttpPost]
        public VMTblMProduct? Add(VMTblMProduct data)
        {
            try
            {
                //upload if image existed
                if (data.ImageFile != null)
                {
                    //upload image process
                    data.Image = product.UploadImage(data.ImageFile, imgFolder);
                    data.ImageFile = null;
                }

                return product.Create(data);
            }
            catch (Exception ex)
            {
                //logging
                Console.WriteLine(ex.Message);
                throw new Exception(ex.ToString());
            }

        }


    }
}

xposweb/xposweb/Controllers/VariantsController.cs
using Microsoft.AspNetCore.Mvc;
using Xpos.Models;
using xposapi.DataModels;
using xposweb.Models;

namespace xposweb.Controllers
{
    public class VariantsController : Controller
    {
        private VariantsModels variant;
        private CategoriesModels categories;

        public VariantsController(IConfiguration _config)
        {
            variant = new VariantsModels(_config["ApiMasterUrl"]);
            categories = new CategoriesModels(_config["ApiMasterUrl"]);
        }

        public IActionResult Index()
        {
            ViewBag.Title = "Variant List";

            List<VMTblMVariant>? data = variant.GetAll();

            return View(data);
        }

        public IActionResult Details(int id)
        {
            ViewBag.Title = "Variant Details";

            VMTblMVariant? data = variant.GetById(id);

            return View(data);
        }

        public IActionResult Create()
        {
            ViewBag.Title = "Create Variant";
            ViewBag.CatData = categories.GetAll();
            return View();

        }

        [HttpPost]
        public VMTblMVariant Add(VMTblMVariant data) => variant.Create(data);


        public IActionResult Edit(int id)
        {
            ViewBag.Title = "Edit Variant";
            VMTblMVariant? data = variant.GetById(id);
            return View(data);
        }
    }
}

xposweb/xposweb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - xposweb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/xposweb.styles.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">xposweb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-link dropdown-toggle text-decoration-none text-black" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    Master
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <li><a class="dropdown-item" asp-controller="Categories" asp-action="Index">Category</a></li>
                                    <li><a class="dropdown-item" asp-controller="Variants" asp-action="Index">Variant</a></li>
                                    <li><a class="dropdown-item" asp-controller="Products" asp-action="Index">Product</a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-link dropdown-toggle text-decoration-none text-black" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    Transaction
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <li><a class="dropdown-item" asp-controller="Orders" asp-action="Index"></i>Order</a></li>
                                    <li><a class="dropdown-item" asp-controller="Orders" asp-action="Index">Order History</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - xposweb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <partial name="_Modal" />

    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

xposweb/xposweb/Views/Shared/_Modal.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="modal" tabindex="-1" id="staticModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" id="staticModalHeader">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="staticModalBody">
                <p>Modal body text goes here.</p>
            </div>
@*             <div class="modal-footer" id="staticModalFooter">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div> *@
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" id="staticModalLg">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header" id="staticModalLgHeader">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="staticModalLgBody">
                <p>Modal body text goes here.</p>
            </div>
@*             <div class="modal-footer" id="staticModalLgFooter">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div> *@
        </div>
    </div>
</div>